const types = {
  ORDER_REGISTER: "@order/ORDER_REGISTER",
  ORDER_REGISTER_SUCCESS: "@order/ORDER_REGISTER_SUCCESS",
  ORDER_GET: "@order/ORDER_GET",
  ORDER_REQUEST: "@order/ORDER_REQUEST",
  ORDER_STATUS: "@order/ORDER_STATUS",
  ORDER_STATUS_SUCCESS: "@order/ORDER_STATUS_SUCCESS"
};
export default types;
