const types = {
  SIZEBUCKET_REGISTER: "@sizeBucket/SIZEBUCKET_REGISTER",
  SIZEBUCKET_REGISTER_SUCCESS: "@sizeBucket/SIZEBUCKET_REGISTER_SUCCESS",
  SIZEBUCKET_GET: "@sizeBucket/SIZEBUCKET_GET",
  SIZEBUCKET_REQUEST: "@sizeBucket/SIZEBUCKET_REQUEST",
};
export default types;
