const types = {
  SIZEBUCKET_REGISTER: "@sizeBucket/SIZEBUCKET_REGISTER",
  SIZEBUCKET_REGISTER_SUCCESS: "@sizeBucket/SIZEBUCKET_REGISTER_SUCCESS",
  SIZEBUCKET_GET: "@sizeBucket/SIZEBUCKET_GET",
  SIZEBUCKET_REQUEST: "@sizeBucket/SIZEBUCKET_REQUEST",
  SIZEBUCKET_UPDATE: "@sizeBucket/SIZEBUCKET_UPDATE",
  SIZEBUCKET_DELETE: "@sizeBucket/SIZEBUCKET_DELETE",
  SIZEBUCKET_DELETE_SUCCESS: "@sizeBucket/SIZEBUCKET_DELETE_SUCCESS",
};
export default types;
