const types = {
  FLAVOR_REGISTER: "@flavor/FLAVOR_REGISTER",
  FLAVOR_REGISTER_SUCCESS: "@flavor/FLAVOR_REGISTER_SUCCESS",
  FLAVOR_GET: "@flavor/FLAVOR_GET",
  FLAVOR_REQUEST: "@flavor/FLAVOR_REQUEST",
  FLAVOR_UPDATE: "@flavor/FLAVOR_UPDATE",
  FLAVOR_DELETE: "@flavor/FLAVOR_DELETE",
  FLAVOR_DELETE_SUCCESS: "@flavor/FLAVOR_DELETE_SUCCESS",
};
export default types;
