const types = {
  PERSONALIZE_REGISTER: "@personalize/PERSONALIZE_REGISTER",
  PERSONALIZE_REGISTER_SUCCESS: "@personalize/PERSONALIZE_REGISTER_SUCCESS",
  PERSONALIZE_GET: "@personalize/PERSONALIZE_GET",
  PERSONALIZE_REQUEST: "@personalize/PERSONALIZE_REQUEST",
  PERSONALIZE_UPDATE: "@personalize/PERSONALIZE_UPDATE",
};
export default types;
